### ISSUE TITLE
Bug: Formatter removing some generics

### ISSUE THREAD

**Issue by PeytonHanel** [alex12058/prettier#1]
It seems to only be generics on the right side of the Type declaration, or in the return declaration of a function. This is the only file I'm having problems with so far.

Normal prettier does not have this same behavior. It keeps the generics.

**Command and rc File**

```sh
prettier --write .
```

```json
{
  "plugins": ["prettier-plugin-svelte", "prettier-plugin-tailwindcss"],
  "overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }],
  "tabWidth": 2,
  "semi": false,
  "arrowParens": "avoid",
  "singleAttributePerLine": true,
  "svelteSortOrder": "scripts-options-markup-styles"
}

```

**Input:**

```ts
export const Some = <T>(value: T): Some<T> => ({ value })
export const None = (): None => ({})
export const isSome = <T>(option: Option<T>): option is Some<T> =>
  "value" in option
export const isNone = <T>(option: Option<T>): option is None =>
  !("value" in option)

export const Ok = <T>(value: T): Ok<T> => ({ ok: true, value })
export const Err = <E>(error: E): Err<E> => ({ ok: false, error })
export const isOk = <T, E>(result: Result<T, E>): result is Ok<T> => result.ok
export const isErr = <T, E>(result: Result<T, E>): result is Err<E> =>
  !result.ok

export async function rfetch(
  input: string | URL | globalThis.Request,
  init?: RequestInit & { fetchOverride?: Function },
): Promise<Result<Response, DOMException | TypeError | unknown>>
```

**Output:**

```ts
export const Some = <T>(value: T): Some => ({ value })
export const None = (): None => ({})
export const isSome = <T>(option: Option): option is Some => "value" in option
export const isNone = <T>(option: Option): option is None =>
  !("value" in option)

export const Ok = <T>(value: T): Ok => ({ ok: true, value })
export const Err = <E>(error: E): Err => ({ ok: false, error })
export const isOk = <T, E>(result: Result): result is Ok => result.ok
export const isErr = <T, E>(result: Result): result is Err => !result.ok

export async function rfetch(
  input: string | URL | globalThis.Request,
  init?: RequestInit & { fetchOverride?: Function },
): Promise
```

**Expected output:**

The expected output should not have all the generics removed.

**Why?**

Because it breaks the typescript code, as seen in this screenshot:
![image](https://github.com/user-attachments/assets/0626dd86-f878-4abf-b028-da040cfc2515)

**Comment by alex12058** [comment]
Hi Peyton,

Thanks for creating the ticket. Could you please confirm which version of `@marketgridsys/prettier` you are using for the input file and the parser or file extension.

If I format the provided input with the typescript parser it is fine and it does not lose the generics.

**Comment by PeytonHanel** [comment]
```json
"devDependencies": {
    "@marketgridsys/prettier": "3.4.0-mgs.2",
    ...
```
The file is `result.ts` and I uploaded the entire file here for your reference.
[result.ts.zip](https://github.com/user-attachments/files/17048875/result.ts.zip)

**Comment by alex12058** [comment]
I'm struggling to reproduce this.

Could you run `prettier --version`. If `prettier` is aliased to `@marketgridsys/prettier@3.4.0-mgs.2` this should print `3.4.0-mgs.2`. Alternatively you can run `which prettier` to see which directory it points at.

Please run `prettier --debug-level debug --debug-check path/to/result.ts` and post the results here.

**Comment by PeytonHanel** [comment]
Hi Alex, 

For some reason `prettier` in my terminal returns `command not found`. I just run it with my `pnpm run format` script, which is `prettier --write .`

I did some digging and the problem is with how your fork interacts with `prettier-plugin-tailwindcss`. When I exclude that from `.prettierrc.json` the bug goes away. The normal prettier formatter doesn't have this problem, so it's a compatibility problem with your fork and the plugin. If this is outside of what you're willing to fix I can just not use the plugin.

I created a repo here that replicates this for you. There are 3 different branches, make sure to run `pnpm i` when switching.
https://gitlab.com/peytonhanel/marketgridsys-prettier-bug

**Comment by alex12058** [comment]
@PeytonHanel  Looking at the pnpm lock file I can see that (the base/vanilla) prettier is a dependency of `prettier-plugin-tailwindcss`. This plugin caused the formatting issue because it was using it's own version of prettier. In order to get the plugin to use the `@marketgridsys/prettier` version of prettier you need to install `@marketgridsys/prettier` aliased as `prettier`.

When you install `@marketgridsys/prettier` with pnpm you can run this command to alias it to `prettier`:
```
pnpm i prettier@npm:@marketgridsys/prettier
```

Remove the unaliased version with:
```
pnpm remove @marketgridsys/prettier
```

I've tested this fix and it resolves the formatting issue where the generics dissapear.
